# Generated by Django 2.1.5 on 2019-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='position',
            field=models.CharField(choices=[('PR', 'President'), ('VP', 'Vice President'), ('HG', 'Honorary Secretary'), ('None', 'Choose position')], default='None', max_length=5),
        ),
    ]
