# Generated by Django 2.1.5 on 2019-03-14 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20190314_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('vote', 'voter')},
        ),
    ]
